epochs : 700
n_look_behind : 10
learning_rate: 1e-3
return_full_sim : False
return_full_sim_epoch_interval : 10
rng_key : 60
debug: False
mse_loss: 1
spectral_energy_loss: 0.007
rate_of_strain_loss: 0.002
mse_weight: 200.0
spectral_weight: 33.53
strain_weight: 104.71
early_stopping: True