experiment:
  name: turbulence_force_corrector
data:
  debug: ${training.debug}
  hr_res: 160
  downscaling_factor: 2
  num_checkpoints: 10
  num_timesteps: 1000
  generate_data_on_fly: true
  precomputed_data: false
  fixed_timestep: false
  dt_max: 0.1
  t_end: 1.0
  snapshot_timepoints:
  - 1.0
  num_snapshots: 1
  use_specific_snapshot_timepoints: true
  return_snapshots: true
  scenarios:
  - 1
  differentiation_mode: 1
training:
  epochs: 700
  n_look_behind: 10
  learning_rate: 0.001
  return_full_sim: false
  return_full_sim_epoch_interval: 10
  rng_key: 60
  debug: false
  mse_loss: 1
  spectral_energy_loss: 0.007
  rate_of_strain_loss: 0.002
  mse_weight: 200.0
  spectral_weight: 33.53
  strain_weight: 104.71
  early_stopping: true
models:
  _target_: corrector_src.model.fno_hd_force_corrector.TurbulenceSGSForceCorrectorFNO
  _name_: fno
  hidden_channels: 13
  n_fourier_layers: 2
  fourier_modes: 14
  shifting_modes: 1
  postprocessing_floor: True
